In [1]:
import pandas as pd

In [2]:
pred = pd.read_csv("../datasets/covid/infer_rslt.csv")
pred.drop(columns={"Unnamed: 0"}, inplace=True)
pred

      y_true  y_pred                                              score
0          3       3  [3.1396974e-04 2.0521908e-04 7.1623304e-04 9.9...
1          3       3  [2.9645584e-04 8.9186040e-05 4.3674232e-04 9.9...
2          3       3  [3.2460969e-04 1.3354393e-04 2.4592137e-04 9.9...
3          3       3  [2.4961308e-04 1.2556925e-04 1.9549744e-04 9.9...
4          3       3  [1.9971735e-03 8.5234911e-05 1.6939481e-03 9.9...
...      ...     ...                                                ...
4243       3       3  [1.9900747e-04 1.2620007e-04 1.7626394e-04 9.9...
4244       1       1  [1.2754698e-05 9.3889940e-01 4.3536426e-04 6.0...
4245       3       1  [6.2500840e-05 9.8361963e-01 3.3338403e-04 1.5...
4246       3       3  [5.2302470e-04 8.4964384e-05 5.3647440e-04 9.9...
4247       1       1  [9.0305102e-06 9.9759007e-01 1.5356576e-03 8.6...

[4248 rows x 3 columns]

In [3]:
for i in range(4):
    irrelavant = pred[pred["y_true"] == i]
    irrelavant_correct = irrelavant[irrelavant["y_pred"]==i]
    print(i,len(irrelavant_correct)/len(irrelavant))

0 0.17073170731707318
1 0.7017045454545454
2 0.5109717868338558
3 0.9131787330316742

In [4]:
pred[pred["y_true"] == 0]

      y_true  y_pred                                              score
37         0       3  [3.9173572e-04 5.2035216e-04 2.9244516e-03 9.9...
39         0       2  [1.4860615e-04 5.8986677e-04 9.9657440e-01 2.6...
261        0       0  [9.9904042e-01 5.1070776e-05 1.1843893e-05 8.9...
263        0       0  [9.9988687e-01 2.4630966e-05 4.8695351e-06 8.3...
366        0       0      [0.968366   0.01492503 0.00380885 0.01290012]
367        0       1  [1.7457455e-04 9.9645150e-01 1.9436309e-03 1.4...
447        0       1  [4.8721172e-06 9.9711764e-01 2.0538071e-04 2.6...
693        0       1  [3.5686052e-04 9.9653000e-01 1.5396038e-04 2.9...
695        0       1  [2.6228139e-05 9.9890363e-01 1.5855515e-04 9.1...
973        0       3  [6.7424821e-04 8.5503090e-04 1.9391929e-04 9.9...
1020       0       1  [1.1524935e-05 9.9773741e-01 6.7217177e-04 1.5...
1023       0       1  [7.1115510e-06 9.9910021e-01 1.4381197e-04 7.4...
1519       0       1  [8.8173792e-06 9.9561751e-01 3.0147329e-03 1.3...
1549       0       3  [2.6439980e-03 2.0028836e-04 1.3865468e-03 9.9...
1551       0       1  [2.1999971e-05 9.9681479e-01 2.4441150e-03 7.1...
1696       0       3  [1.8356279e-04 8.6740438e-05 4.5695438e-04 9.9...
1698       0       3  [3.0927270e-04 8.9971742e-05 5.0414109e-04 9.9...
1701       0       3  [7.3414372e-04 6.9547314e-03 7.3293975e-04 9.9...
1703       0       1  [4.5313914e-06 9.9837059e-01 2.0503133e-04 1.4...
2002       0       3  [7.4128353e-04 1.1223323e-04 6.8146520e-04 9.9...
2007       0       2  [1.6831543e-03 5.1037292e-05 9.1041982e-01 8.7...
2090       0       3  [3.9802656e-02 3.1303149e-04 8.6309068e-04 9.5...
2095       0       0  [8.1110090e-01 1.8658912e-01 2.5360694e-04 2.0...
2405       0       0  [9.9977416e-01 2.9546951e-05 5.1186789e-06 1.9...
2407       0       0  [9.9994266e-01 2.4120825e-05 3.5046041e-06 2.9...
2431       0       2  [5.0360275e-05 7.7998999e-04 9.9840587e-01 7.6...
2485       0       1  [5.7702226e-05 9.9756444e-01 8.5973108e-05 2.2...
2487       0       1  [2.0180361e-05 9.9889237e-01 7.4329546e-05 1.0...
2806       0       2  [2.6583314e-04 6.7744859e-02 9.2889673e-01 3.0...
2807       0       1  [2.6773764e-06 9.9751401e-01 4.1518567e-04 2.0...
3358       0       0      [0.7559234  0.23512249 0.00360921 0.0053449 ]
3359       0       1  [9.6969731e-04 9.9765104e-01 8.6649938e-04 5.1...
3438       0       2  [5.8844971e-04 1.6275676e-01 8.2118213e-01 1.5...
3439       0       1  [6.7503670e-06 9.9663514e-01 1.7778077e-03 1.5...
3493       0       1  [3.43440712e-04 9.94215310e-01 1.00379955e-04 ...
3495       0       1  [1.0972396e-04 9.9821007e-01 4.3753949e-05 1.6...
3823       0       1  [6.2230852e-06 9.9410546e-01 3.7263492e-03 2.1...
3861       0       3  [1.4837217e-04 2.5131306e-04 2.8890229e-04 9.9...
3863       0       1  [2.3876081e-04 9.6776420e-01 1.7119822e-03 3.0...
4213       0       1  [2.6014755e-02 9.6370733e-01 1.0062656e-04 1.0...
4215       0       1  [1.2964869e-03 9.9748647e-01 6.5465189e-05 1.1...

In [5]:
map=dict(zip([i for i in range(4)],['positive', 'neutral', 'negative', 'unrelated']))
map

{0: 'positive', 1: 'neutral', 2: 'negative', 3: 'unrelated'}

In [6]:
pred["y_true"] = pred["y_true"].apply(lambda x: map[x])
pred["y_pred"] = pred["y_pred"].apply(lambda x: map[x])
pred

         y_true     y_pred                                              score
0     unrelated  unrelated  [3.1396974e-04 2.0521908e-04 7.1623304e-04 9.9...
1     unrelated  unrelated  [2.9645584e-04 8.9186040e-05 4.3674232e-04 9.9...
2     unrelated  unrelated  [3.2460969e-04 1.3354393e-04 2.4592137e-04 9.9...
3     unrelated  unrelated  [2.4961308e-04 1.2556925e-04 1.9549744e-04 9.9...
4     unrelated  unrelated  [1.9971735e-03 8.5234911e-05 1.6939481e-03 9.9...
...         ...        ...                                                ...
4243  unrelated  unrelated  [1.9900747e-04 1.2620007e-04 1.7626394e-04 9.9...
4244    neutral    neutral  [1.2754698e-05 9.3889940e-01 4.3536426e-04 6.0...
4245  unrelated    neutral  [6.2500840e-05 9.8361963e-01 3.3338403e-04 1.5...
4246  unrelated  unrelated  [5.2302470e-04 8.4964384e-05 5.3647440e-04 9.9...
4247    neutral    neutral  [9.0305102e-06 9.9759007e-01 1.5356576e-03 8.6...

[4248 rows x 3 columns]

In [7]:
test = pd.read_csv("../datasets/covid/test_NLI_M.csv",header=None,sep="\t")
test.columns = ["id", "y_true", "category", "text"]
test

,id,y_true,category,text
0,1230448944762826752,unrelated,politics,#badjokethursday I hit my girlfriend over the...
1,1230448944762826752,unrelated,economy,#badjokethursday I hit my girlfriend over the...
2,1230448944762826752,unrelated,foreign,#badjokethursday I hit my girlfriend over the...
3,1230448944762826752,unrelated,culture,#badjokethursday I hit my girlfriend over the...
4,1230448944762826752,unrelated,situation,#badjokethursday I hit my girlfriend over the...
...,...,...,...,...
4243,1234156973513416704,unrelated,culture,Gee. â€œ70-year-old man in Hubei Province was in...
4244,1234156973513416704,neutral,situation,Gee. â€œ70-year-old man in Hubei Province was in...
4245,1234156973513416704,unrelated,measures,Gee. â€œ70-year-old man in Hubei Province was in...
4246,1234156973513416704,unrelated,racism,Gee. â€œ70-year-old man in Hubei Province was in...
4247,1234156973513416704,neutral,overall,Gee. â€œ70-year-old man in Hubei Province was in...

In [8]:
result = test.merge(pred, on = "y_true")
result

,id,y_true,category,text,y_pred,score
0,1230448944762826752,unrelated,politics,#badjokethursday I hit my girlfriend over the...,unrelated,[3.1396974e-04 2.0521908e-04 7.1623304e-04 9.9...
1,1230448944762826752,unrelated,politics,#badjokethursday I hit my girlfriend over the...,unrelated,[2.9645584e-04 8.9186040e-05 4.3674232e-04 9.9...
2,1230448944762826752,unrelated,politics,#badjokethursday I hit my girlfriend over the...,unrelated,[3.2460969e-04 1.3354393e-04 2.4592137e-04 9.9...
3,1230448944762826752,unrelated,politics,#badjokethursday I hit my girlfriend over the...,unrelated,[2.4961308e-04 1.2556925e-04 1.9549744e-04 9.9...
4,1230448944762826752,unrelated,politics,#badjokethursday I hit my girlfriend over the...,unrelated,[1.9971735e-03 8.5234911e-05 1.6939481e-03 9.9...
...,...,...,...,...,...,...
12730637,1221407202180620288,positive,overall,Pope Francis praises China's efforts to contai...,neutral,[6.2230852e-06 9.9410546e-01 3.7263492e-03 2.1...
12730638,1221407202180620288,positive,overall,Pope Francis praises China's efforts to contai...,unrelated,[1.4837217e-04 2.5131306e-04 2.8890229e-04 9.9...
12730639,1221407202180620288,positive,overall,Pope Francis praises China's efforts to contai...,neutral,[2.3876081e-04 9.6776420e-01 1.7119822e-03 3.0...
12730640,1221407202180620288,positive,overall,Pope Francis praises China's efforts to contai...,neutral,[2.6014755e-02 9.6370733e-01 1.0062656e-04 1.0...
12730641,1221407202180620288,positive,overall,Pope Francis praises China's efforts to contai...,neutral,[1.2964869e-03 9.9748647e-01 6.5465189e-05 1.1...

# Aspect Detection

In [9]:
map1=dict(zip(['positive', 'neutral', 'negative', 'unrelated'], [0, 0, 0, 1]))
map1

{'positive': 0, 'neutral': 0, 'negative': 0, 'unrelated': 1}

In [10]:
detection = result.copy()
detection["y_true"] = detection["y_true"].apply(lambda x: map1[x])
detection["y_pred"] = detection["y_pred"].apply(lambda x: map1[x])
detection

,id,y_true,category,text,y_pred,score
0,1230448944762826752,1,politics,#badjokethursday I hit my girlfriend over the...,1,[3.1396974e-04 2.0521908e-04 7.1623304e-04 9.9...
1,1230448944762826752,1,politics,#badjokethursday I hit my girlfriend over the...,1,[2.9645584e-04 8.9186040e-05 4.3674232e-04 9.9...
2,1230448944762826752,1,politics,#badjokethursday I hit my girlfriend over the...,1,[3.2460969e-04 1.3354393e-04 2.4592137e-04 9.9...
3,1230448944762826752,1,politics,#badjokethursday I hit my girlfriend over the...,1,[2.4961308e-04 1.2556925e-04 1.9549744e-04 9.9...
4,1230448944762826752,1,politics,#badjokethursday I hit my girlfriend over the...,1,[1.9971735e-03 8.5234911e-05 1.6939481e-03 9.9...
...,...,...,...,...,...,...
12730637,1221407202180620288,0,overall,Pope Francis praises China's efforts to contai...,0,[6.2230852e-06 9.9410546e-01 3.7263492e-03 2.1...
12730638,1221407202180620288,0,overall,Pope Francis praises China's efforts to contai...,1,[1.4837217e-04 2.5131306e-04 2.8890229e-04 9.9...
12730639,1221407202180620288,0,overall,Pope Francis praises China's efforts to contai...,0,[2.3876081e-04 9.6776420e-01 1.7119822e-03 3.0...
12730640,1221407202180620288,0,overall,Pope Francis praises China's efforts to contai...,0,[2.6014755e-02 9.6370733e-01 1.0062656e-04 1.0...
12730641,1221407202180620288,0,overall,Pope Francis praises China's efforts to contai...,0,[1.2964869e-03 9.9748647e-01 6.5465189e-05 1.1...

In [11]:
from sklearn.metrics import f1_score
print("The Aspect Detection Task:")
for i in detection.category.unique():
    tmp = detection[detection["category"]==i]
    macrof1 = f1_score(tmp["y_true"], tmp["y_pred"], average='macro')
    microf1 = f1_score(tmp["y_true"], tmp["y_pred"], average='micro')
    print(f"Category: {i}\tMacro F1: {macrof1}\tMicro F1: {microf1}")

The Aspect Detection Task:
Category: politics	Macro F1: 0.5477700737248246	Micro F1: 0.9115267586095388
Category: economy	Macro F1: 0.49508727244694173	Micro F1: 0.9129708411990052
Category: foreign	Macro F1: 0.5120097657639627	Micro F1: 0.9123398029670242
Category: culture	Macro F1: 0.4858508559695843	Micro F1: 0.9131062563452458
Category: situation	Macro F1: 0.6144802324671572	Micro F1: 0.9122272686681114
Category: measures	Macro F1: 0.54562872074565	Micro F1: 0.9126074716223497
Category: racism	Macro F1: 0.5501319512630178	Micro F1: 0.9113665720522338
Category: overall	Macro F1: 0.861881251017803	Micro F1: 0.8934784897477434

# Sentiment Classification

In [78]:
classification = result.copy()
classification = classification[classification["y_true"] != "unrelated"]
classification.reset_index(drop=True, inplace=True)
classification

,id,y_true,category,text,y_pred,score
0,1251997190559608832,negative,politics,"Embarrassing. At the very least, Trudeau could...",negative,[1.1432102e-04 8.0572499e-04 6.4865404e-01 3.5...
1,1251997190559608832,negative,politics,"Embarrassing. At the very least, Trudeau could...",negative,[4.36586764e-04 1.07718783e-03 8.89834344e-01 ...
2,1251997190559608832,negative,politics,"Embarrassing. At the very least, Trudeau could...",negative,[3.3736104e-04 1.6709736e-04 7.7967900e-01 2.1...
3,1251997190559608832,negative,politics,"Embarrassing. At the very least, Trudeau could...",positive,[0.9622647 0.01557479 0.00422049 0.01794005]
4,1251997190559608832,negative,politics,"Embarrassing. At the very least, Trudeau could...",neutral,[7.8497635e-04 9.9682319e-01 9.5534837e-04 1.4...
...,...,...,...,...,...,...
227341,1221407202180620288,positive,overall,Pope Francis praises China's efforts to contai...,neutral,[6.2230852e-06 9.9410546e-01 3.7263492e-03 2.1...
227342,1221407202180620288,positive,overall,Pope Francis praises China's efforts to contai...,unrelated,[1.4837217e-04 2.5131306e-04 2.8890229e-04 9.9...
227343,1221407202180620288,positive,overall,Pope Francis praises China's efforts to contai...,neutral,[2.3876081e-04 9.6776420e-01 1.7119822e-03 3.0...
227344,1221407202180620288,positive,overall,Pope Francis praises China's efforts to contai...,neutral,[2.6014755e-02 9.6370733e-01 1.0062656e-04 1.0...
227345,1221407202180620288,positive,overall,Pope Francis praises China's efforts to contai...,neutral,[1.2964869e-03 9.9748647e-01 6.5465189e-05 1.1...

In [79]:
classification["score"] = classification["score"].apply(lambda x: [ float(i) for i in x[1:-1].split(" ") if len(i)>0 ][:-1])
classification["y_pred"] = classification["score"].apply(lambda x: x.index(max(x)))
map2=dict(zip(['positive', 'neutral', 'negative'], [0, 1, 2]))
classification["y_true"] = classification["y_true"].apply(lambda x: map2[x])
classification[classification["y_pred"] == "unrelated"]

/Users/Edward/opt/anaconda3/lib/python3.8/site-packages/pandas/core/ops/array_ops.py:253: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  res_values = method(rvalues)

Empty DataFrame
Columns: [id, y_true, category, text, y_pred, score]
Index: []

In [80]:
classification

,id,y_true,category,text,y_pred,score
0,1251997190559608832,2,politics,"Embarrassing. At the very least, Trudeau could...",2,"[0.00011432102, 0.00080572499, 0.64865404]"
1,1251997190559608832,2,politics,"Embarrassing. At the very least, Trudeau could...",2,"[0.000436586764, 0.00107718783, 0.889834344]"
2,1251997190559608832,2,politics,"Embarrassing. At the very least, Trudeau could...",2,"[0.00033736104, 0.00016709736, 0.779679]"
3,1251997190559608832,2,politics,"Embarrassing. At the very least, Trudeau could...",0,"[0.9622647, 0.01557479, 0.00422049]"
4,1251997190559608832,2,politics,"Embarrassing. At the very least, Trudeau could...",1,"[0.00078497635, 0.99682319, 0.00095534837]"
...,...,...,...,...,...,...
227341,1221407202180620288,0,overall,Pope Francis praises China's efforts to contai...,1,"[6.2230852e-06, 0.99410546, 0.0037263492]"
227342,1221407202180620288,0,overall,Pope Francis praises China's efforts to contai...,2,"[0.00014837217, 0.00025131306, 0.00028890229]"
227343,1221407202180620288,0,overall,Pope Francis praises China's efforts to contai...,1,"[0.00023876081, 0.9677642, 0.0017119822]"
227344,1221407202180620288,0,overall,Pope Francis praises China's efforts to contai...,1,"[0.026014755, 0.96370733, 0.00010062656]"
227345,1221407202180620288,0,overall,Pope Francis praises China's efforts to contai...,1,"[0.0012964869, 0.99748647, 6.5465189e-05]"

In [81]:
print("The Sentiment Classification Task:")
for i in classification.category.unique():
    tmp = classification[classification["category"]==i]
    macrof1 = f1_score(tmp["y_true"], tmp["y_pred"], average='macro')
    microf1 = f1_score(tmp["y_true"], tmp["y_pred"], average='micro')
    print(f"Category: {i}\tMacro F1: {macrof1}\tMicro F1: {microf1}")

The Sentiment Classification Task:
Category: politics	Macro F1: 0.42002030084081493	Micro F1: 0.7200785994998214
Category: overall	Macro F1: 0.5140099604940075	Micro F1: 0.7349001506459967
Category: racism	Macro F1: 0.3932526250395258	Micro F1: 0.7153639430499171
Category: culture	Macro F1: 0.497267059005478	Micro F1: 0.7378984651711924
Category: foreign	Macro F1: 0.3064903462122926	Micro F1: 0.7106693010619906
Category: situation	Macro F1: 0.46719731731332076	Micro F1: 0.7429900461908789
Category: measures	Macro F1: 0.5434157950743236	Micro F1: 0.7243653382498937
Category: economy	Macro F1: 0.5023618280499015	Micro F1: 0.733260751224823

# Joint Task

In [82]:
print("The Joint Task:")
for i in result.category.unique():
    tmp = result[result["category"]==i]
    macrof1 = f1_score(tmp["y_true"], tmp["y_pred"], average='macro')
    microf1 = f1_score(tmp["y_true"], tmp["y_pred"], average='micro')
    print(f"Category: {i}\tMacro F1: {macrof1}\tMicro F1: {microf1}")

The Joint Task:
Category: politics	Macro F1: 0.29038821959148386	Micro F1: 0.9094101822962128
Category: economy	Macro F1: 0.25232602032504486	Micro F1: 0.9125588771999908
Category: foreign	Macro F1: 0.26605823604564016	Micro F1: 0.9113323624591846
Category: culture	Macro F1: 0.2451384727350612	Micro F1: 0.9129209348796484
Category: situation	Macro F1: 0.3355559126822564	Micro F1: 0.908349569025695
Category: measures	Macro F1: 0.29489318378519913	Micro F1: 0.9108340510768491
Category: racism	Macro F1: 0.2925005494108855	Micro F1: 0.9091026894995731
Category: overall	Macro F1: 0.5377483699077515	Micro F1: 0.8421664114608057